# Generated by Django 3.2.8 on 2021-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='profile',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
    ]
