# Generated by Django 3.2.8 on 2021-11-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211105_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='medal',
        ),
    ]
