# Generated by Django 3.2.9 on 2021-11-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gendre',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=6),
        ),
    ]
