# Generated by Django 3.2.9 on 2021-11-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_gendre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gendre',
            new_name='gender',
        ),
    ]
