# Generated by Django 4.0 on 2021-12-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211123_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_male.jpg', upload_to='profile_pics'),
        ),
    ]
